name: Worker Test

on:
  workflow_dispatch:

jobs:  
  check:  
    runs-on: ubuntu-24.04  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
  
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '22.x' 
          
      - name: Check Aliases
        run: alias
        
      - name: Try to su
        run: sudo add-apt-repository ppa:zhangsongcui3371/fastfetch && sudo apt update
        
      - name: Remove junks
        run: sudo apt autoremove -y

      - name: Install some packages
        run: sudo apt install fastfetch lolcat -y
        
      - name: Print system version
        run: sudo fastfetch -c all.jsonc | lolcat -t -a
      
      - name: Check system IP
        run: curl 4.ipw.cn
      
      - name: Check system IP (v6)
        run: curl 6.ipw.cn
        
      - name: Check system IP (4+6)
        run: curl test.ipw.cn
