name: Worker Test

on:
  workflow_dispatch:

jobs:  
  check:  
    runs-on: ubuntu-24.04  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
  
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '22.x' 
          
      - name: Check Aliases
        run: alias
        
      - name: Try to su
        run: sudo add-apt-repository ppa:zhangsongcui3371/fastfetch && sudo apt update
        
      - name: Remove junks
        run: sudo apt autoremove -y

      - name: Install some packages
        run: sudo apt install fastfetch lolcat -y
        
      - name: Print system version
        run: sudo fastfetch -c all.jsonc | lolcat -t -a
      
      - name: Check system IP
        run: curl 4.ipw.cn

      - name: Install xvfb and x11vnc
        run: sudo apt install xvfb x11vnc -y

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &

      - name: Set x11vnc password
        run: |
          mkdir -p ~/.vnc
          x11vnc -storepasswd 12345678 ~/.vnc/passwd

      - name: Allow VNC port through ufw
        run: |
          sudo ufw allow 5900
          sudo ufw enable
          sudo ufw status

      - name: Start x11vnc
        run: |
          export DISPLAY=:99
          x11vnc -forever -usepw -display :99 &

      - name: Verify x11vnc is running
        run: |
          sleep 5  # Give x11vnc some time to start
          netstat -tuln | grep 5900

      - name: Sleep for 600 seconds
        run: sleep 600
